/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rofat.blooddonation;

import com.rofat.blooddonation.Class.Api;
import dto.Inbox;
import dto.User;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author rofat
 */
public class DonateOrderInbox extends javax.swing.JFrame {

    /**
     * Creates new form DonateOrderInbox
     */
    Api api = new Api();
    User usr = new User();

    public DonateOrderInbox() throws IOException {
        initComponents();
    }

    public DonateOrderInbox(User user) throws IOException {
        initComponents();
        loadData(user);
    }

    private void loadData(User user) throws IOException {
        this.usr = user;
        lbFullName.setText(user.getName());
        List<Inbox> inbx = api.getInbox(user.getEmail());

        for (int i = 0; i < inbx.size(); i++) {
            switch (i) {
                case 0:
                    lbHeader0.setText(inbx.get(0).getHeader());
                    lbDate0.setText(inbx.get(0).getDate());
                    lbBody0.setText(inbx.get(0).getBody());
                    pnInbox1.setVisible(false);
                    pnInbox2.setVisible(false);
                    pnInbox3.setVisible(false);
                    break;
                case 1:
                    lbHeader1.setText(inbx.get(1).getHeader());
                    lbDate1.setText(inbx.get(1).getDate());
                    lbBody1.setText(inbx.get(1).getBody());
                    pnInbox1.setVisible(true);
                    pnInbox2.setVisible(false);
                    pnInbox3.setVisible(false);
                    break;
                case 2:
                    lbHeader2.setText(inbx.get(2).getHeader());
                    lbDate2.setText(inbx.get(2).getDate());
                    lbBody2.setText(inbx.get(2).getBody());
                    pnInbox2.setVisible(true);
                    pnInbox3.setVisible(false);
                    break;
                case 3:
                    lbHeader3.setText(inbx.get(3).getHeader());
                    lbDate3.setText(inbx.get(3).getDate());
                    lbBody3.setText(inbx.get(3).getBody());
                    pnInbox3.setVisible(true);
                    break;

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogo = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        lbJoin = new javax.swing.JLabel();
        lbBack = new javax.swing.JLabel();
        pnInbox0 = new javax.swing.JPanel();
        lbHeader0 = new javax.swing.JLabel();
        lbDate0 = new javax.swing.JLabel();
        lbBody0 = new javax.swing.JLabel();
        lbSeeDetail0 = new javax.swing.JLabel();
        lbBlood0 = new javax.swing.JLabel();
        pnInbox1 = new javax.swing.JPanel();
        lbHeader1 = new javax.swing.JLabel();
        lbDate1 = new javax.swing.JLabel();
        lbBody1 = new javax.swing.JLabel();
        lbSeeDetail1 = new javax.swing.JLabel();
        lbBlood1 = new javax.swing.JLabel();
        pnInbox2 = new javax.swing.JPanel();
        lbHeader2 = new javax.swing.JLabel();
        lbDate2 = new javax.swing.JLabel();
        lbBody2 = new javax.swing.JLabel();
        lbSeeDetail2 = new javax.swing.JLabel();
        lbBlood2 = new javax.swing.JLabel();
        pnInbox3 = new javax.swing.JPanel();
        lbHeader3 = new javax.swing.JLabel();
        lbDate3 = new javax.swing.JLabel();
        lbBody3 = new javax.swing.JLabel();
        lbSeeDetail3 = new javax.swing.JLabel();
        lbBlood3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 700));

        lbLogo.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\icons8_male_user_70px_1.png")); // NOI18N

        lbFullName.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbFullName.setText("Full Name");

        lbJoin.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbJoin.setText("Joined");

        lbBack.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\icons8_back_arrow_50px.png")); // NOI18N
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
        });

        pnInbox0.setBackground(new java.awt.Color(204, 204, 204));
        pnInbox0.setPreferredSize(new java.awt.Dimension(540, 100));

        lbHeader0.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbHeader0.setText("Dear Name,");

        lbDate0.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbDate0.setForeground(new java.awt.Color(51, 51, 51));
        lbDate0.setText("Date");

        lbBody0.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbBody0.setForeground(new java.awt.Color(51, 51, 51));
        lbBody0.setText("Body");

        lbSeeDetail0.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbSeeDetail0.setForeground(new java.awt.Color(255, 0, 0));
        lbSeeDetail0.setText("See Detail");

        lbBlood0.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\icons8_drop_of_blood_50px.png")); // NOI18N

        javax.swing.GroupLayout pnInbox0Layout = new javax.swing.GroupLayout(pnInbox0);
        pnInbox0.setLayout(pnInbox0Layout);
        pnInbox0Layout.setHorizontalGroup(
                pnInbox0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnInbox0Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnInbox0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnInbox0Layout.createSequentialGroup()
                                                .addComponent(lbBody0)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbSeeDetail0))
                                        .addGroup(pnInbox0Layout.createSequentialGroup()
                                                .addGroup(pnInbox0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbHeader0)
                                                        .addComponent(lbDate0))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                                                .addComponent(lbBlood0)))
                                .addGap(30, 30, 30))
        );
        pnInbox0Layout.setVerticalGroup(
                pnInbox0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnInbox0Layout.createSequentialGroup()
                                .addGroup(pnInbox0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnInbox0Layout.createSequentialGroup()
                                                .addComponent(lbHeader0)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbDate0))
                                        .addComponent(lbBlood0))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnInbox0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbBody0)
                                        .addComponent(lbSeeDetail0))
                                .addGap(0, 2, Short.MAX_VALUE))
        );

        pnInbox1.setBackground(new java.awt.Color(204, 204, 204));
        pnInbox1.setPreferredSize(new java.awt.Dimension(540, 100));

        lbHeader1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbHeader1.setText("Dear Name,");

        lbDate1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbDate1.setForeground(new java.awt.Color(51, 51, 51));
        lbDate1.setText("Date");

        lbBody1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbBody1.setForeground(new java.awt.Color(51, 51, 51));
        lbBody1.setText("Body");

        lbSeeDetail1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbSeeDetail1.setForeground(new java.awt.Color(255, 0, 0));
        lbSeeDetail1.setText("See Detail");

        lbBlood1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\icons8_drop_of_blood_50px.png")); // NOI18N

        javax.swing.GroupLayout pnInbox1Layout = new javax.swing.GroupLayout(pnInbox1);
        pnInbox1.setLayout(pnInbox1Layout);
        pnInbox1Layout.setHorizontalGroup(
                pnInbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnInbox1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnInbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnInbox1Layout.createSequentialGroup()
                                                .addComponent(lbBody1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbSeeDetail1))
                                        .addGroup(pnInbox1Layout.createSequentialGroup()
                                                .addGroup(pnInbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbHeader1)
                                                        .addComponent(lbDate1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                                                .addComponent(lbBlood1)))
                                .addGap(30, 30, 30))
        );
        pnInbox1Layout.setVerticalGroup(
                pnInbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnInbox1Layout.createSequentialGroup()
                                .addGroup(pnInbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnInbox1Layout.createSequentialGroup()
                                                .addComponent(lbHeader1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbDate1))
                                        .addComponent(lbBlood1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnInbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbBody1)
                                        .addComponent(lbSeeDetail1))
                                .addGap(0, 10, Short.MAX_VALUE))
        );

        pnInbox2.setBackground(new java.awt.Color(204, 204, 204));
        pnInbox2.setPreferredSize(new java.awt.Dimension(540, 100));

        lbHeader2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbHeader2.setText("Dear Name,");

        lbDate2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbDate2.setForeground(new java.awt.Color(51, 51, 51));
        lbDate2.setText("Date");

        lbBody2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbBody2.setForeground(new java.awt.Color(51, 51, 51));
        lbBody2.setText("Body");

        lbSeeDetail2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbSeeDetail2.setForeground(new java.awt.Color(255, 0, 0));
        lbSeeDetail2.setText("See Detail");

        lbBlood2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\icons8_drop_of_blood_50px.png")); // NOI18N

        javax.swing.GroupLayout pnInbox2Layout = new javax.swing.GroupLayout(pnInbox2);
        pnInbox2.setLayout(pnInbox2Layout);
        pnInbox2Layout.setHorizontalGroup(
                pnInbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnInbox2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnInbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnInbox2Layout.createSequentialGroup()
                                                .addComponent(lbBody2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbSeeDetail2))
                                        .addGroup(pnInbox2Layout.createSequentialGroup()
                                                .addGroup(pnInbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbHeader2)
                                                        .addComponent(lbDate2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                                                .addComponent(lbBlood2)))
                                .addGap(30, 30, 30))
        );
        pnInbox2Layout.setVerticalGroup(
                pnInbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnInbox2Layout.createSequentialGroup()
                                .addGroup(pnInbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnInbox2Layout.createSequentialGroup()
                                                .addComponent(lbHeader2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbDate2))
                                        .addComponent(lbBlood2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnInbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbBody2)
                                        .addComponent(lbSeeDetail2))
                                .addGap(0, 7, Short.MAX_VALUE))
        );

        pnInbox3.setBackground(new java.awt.Color(204, 204, 204));
        pnInbox3.setPreferredSize(new java.awt.Dimension(540, 100));

        lbHeader3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbHeader3.setText("Dear Name,");

        lbDate3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbDate3.setForeground(new java.awt.Color(51, 51, 51));
        lbDate3.setText("Date");

        lbBody3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbBody3.setForeground(new java.awt.Color(51, 51, 51));
        lbBody3.setText("Body");

        lbSeeDetail3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbSeeDetail3.setForeground(new java.awt.Color(255, 0, 0));
        lbSeeDetail3.setText("See Detail");

        lbBlood3.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\icons8_drop_of_blood_50px.png")); // NOI18N

        javax.swing.GroupLayout pnInbox3Layout = new javax.swing.GroupLayout(pnInbox3);
        pnInbox3.setLayout(pnInbox3Layout);
        pnInbox3Layout.setHorizontalGroup(
                pnInbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnInbox3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnInbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnInbox3Layout.createSequentialGroup()
                                                .addComponent(lbBody3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbSeeDetail3))
                                        .addGroup(pnInbox3Layout.createSequentialGroup()
                                                .addGroup(pnInbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbHeader3)
                                                        .addComponent(lbDate3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                                                .addComponent(lbBlood3)))
                                .addGap(30, 30, 30))
        );
        pnInbox3Layout.setVerticalGroup(
                pnInbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnInbox3Layout.createSequentialGroup()
                                .addGroup(pnInbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnInbox3Layout.createSequentialGroup()
                                                .addComponent(lbHeader3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbDate3))
                                        .addComponent(lbBlood3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnInbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbBody3)
                                        .addComponent(lbSeeDetail3))
                                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbBack)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbFullName)
                                                        .addComponent(lbJoin))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbLogo))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pnInbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pnInbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pnInbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pnInbox0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbLogo)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbBack)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lbFullName)
                                                                .addGap(1, 1, 1)
                                                                .addComponent(lbJoin)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(pnInbox0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnInbox2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnInbox1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(pnInbox3, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        // TODO add your handling code here:
        HomePage hp;
        try {
            hp = new HomePage(usr);
            hp.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(DonateOrderInbox.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lbBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonateOrderInbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonateOrderInbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonateOrderInbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonateOrderInbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DonateOrderInbox().setVisible(true);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbBack;
    private javax.swing.JLabel lbBlood0;
    private javax.swing.JLabel lbBlood1;
    private javax.swing.JLabel lbBlood2;
    private javax.swing.JLabel lbBlood3;
    private javax.swing.JLabel lbBody0;
    private javax.swing.JLabel lbBody1;
    private javax.swing.JLabel lbBody2;
    private javax.swing.JLabel lbBody3;
    private javax.swing.JLabel lbDate0;
    private javax.swing.JLabel lbDate1;
    private javax.swing.JLabel lbDate2;
    private javax.swing.JLabel lbDate3;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbHeader0;
    private javax.swing.JLabel lbHeader1;
    private javax.swing.JLabel lbHeader2;
    private javax.swing.JLabel lbHeader3;
    private javax.swing.JLabel lbJoin;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbSeeDetail0;
    private javax.swing.JLabel lbSeeDetail1;
    private javax.swing.JLabel lbSeeDetail2;
    private javax.swing.JLabel lbSeeDetail3;
    private javax.swing.JPanel pnInbox0;
    private javax.swing.JPanel pnInbox1;
    private javax.swing.JPanel pnInbox2;
    private javax.swing.JPanel pnInbox3;
    // End of variables declaration//GEN-END:variables
}
