/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rofat.blooddonation;

import com.rofat.blooddonation.Class.Api;
import dto.BloodRequest;
import dto.User;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author rofat
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form testJframe
     *
     * @throws java.io.IOException
     */
    Api api = new Api();
    User usr = new User();
    List<BloodRequest> bloodRequests = api.getRequests();
    public HomePage() throws IOException {
        initComponents();
        SetUIContent(bloodRequests);
    }
    public HomePage(User usr) throws IOException {
        initComponents();
       
        SetUIContent(bloodRequests);
        this.usr=usr;
    }
    private void SetUIContent(List<BloodRequest> bloodRequests) throws IOException {
        try{
System.out.println(bloodRequests.get(0).getRequestEmail());
        User userReq = api.getUser(bloodRequests.get(0).getRequestEmail());
        lbFullName.setText(userReq.getName());
        lbAddress.setText(userReq.getAddress().toString());
        lbBloodType.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\"+userReq.getBloodType()+".png"));
        }
catch(Exception e){
}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JLabel();
        lbMenu = new javax.swing.JLabel();
        lbNotification = new javax.swing.JLabel();
        lbDonate = new javax.swing.JLabel();
        lbDonateBlood = new javax.swing.JLabel();
        lbOrderBlood = new javax.swing.JLabel();
        lbFindDonor = new javax.swing.JLabel();
        lbHospital = new javax.swing.JLabel();
        lbReport = new javax.swing.JLabel();
        lbBloodRequest = new javax.swing.JLabel();
        lbSeeAll = new javax.swing.JLabel();
        pnBloodRequest = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbLocation = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbBtnDonate = new javax.swing.JLabel();
        lbBloodType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 700));

        banner.setBackground(new java.awt.Color(153, 0, 102));
        banner.setForeground(new java.awt.Color(153, 0, 153));
        banner.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        banner.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\menu-banner.png")); // NOI18N
        banner.setToolTipText("");

        lbMenu.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\menu.png")); // NOI18N

        lbNotification.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\notification.png")); // NOI18N

        lbDonate.setBackground(new java.awt.Color(204, 204, 204));
        lbDonate.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\inbox.png")); // NOI18N
        lbDonate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        lbDonate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDonateMouseClicked(evt);
            }
        });

        lbDonateBlood.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\donate-blood.png")); // NOI18N
        lbDonateBlood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        lbOrderBlood.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\order-blood.png")); // NOI18N
        lbOrderBlood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        lbFindDonor.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\findDonor.png")); // NOI18N
        lbFindDonor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        lbHospital.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\hospital-.png")); // NOI18N
        lbHospital.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));

        lbReport.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\report-.png")); // NOI18N
        lbReport.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));

        lbBloodRequest.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbBloodRequest.setForeground(new java.awt.Color(255, 0, 0));
        lbBloodRequest.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\dropblood.png")); // NOI18N
        lbBloodRequest.setText("BLOOD REQUEST");

        lbSeeAll.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbSeeAll.setForeground(new java.awt.Color(255, 0, 0));
        lbSeeAll.setText("See All");

        pnBloodRequest.setBackground(new java.awt.Color(204, 204, 204));
        pnBloodRequest.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        lbName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(102, 102, 102));
        lbName.setText("Name");

        lbAddress.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbAddress.setText("Address");

        lbLocation.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbLocation.setForeground(new java.awt.Color(102, 102, 102));
        lbLocation.setText("Location");

        lbFullName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbFullName.setText("Full Name");

        lbTime.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbTime.setForeground(new java.awt.Color(102, 102, 102));
        lbTime.setText("Time");

        lbBtnDonate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbBtnDonate.setForeground(new java.awt.Color(255, 0, 0));
        lbBtnDonate.setText("DONATE");

        lbBloodType.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\bloodType.png")); // NOI18N

        javax.swing.GroupLayout pnBloodRequestLayout = new javax.swing.GroupLayout(pnBloodRequest);
        pnBloodRequest.setLayout(pnBloodRequestLayout);
        pnBloodRequestLayout.setHorizontalGroup(
            pnBloodRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBloodRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBloodRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTime)
                    .addComponent(lbName)
                    .addComponent(lbAddress)
                    .addComponent(lbLocation)
                    .addComponent(lbFullName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnBloodRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBloodRequestLayout.createSequentialGroup()
                        .addComponent(lbBloodType)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBloodRequestLayout.createSequentialGroup()
                        .addComponent(lbBtnDonate)
                        .addGap(32, 32, 32))))
        );
        pnBloodRequestLayout.setVerticalGroup(
            pnBloodRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBloodRequestLayout.createSequentialGroup()
                .addGroup(pnBloodRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBloodRequestLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbName)
                        .addGap(4, 4, 4)
                        .addComponent(lbFullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocation)
                        .addGap(6, 6, 6)
                        .addComponent(lbAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTime))
                    .addGroup(pnBloodRequestLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbBloodType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbBtnDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbMenu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNotification))
                        .addComponent(banner, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbDonate)
                                .addComponent(lbFindDonor))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbDonateBlood)
                                .addComponent(lbHospital))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbReport)
                                .addComponent(lbOrderBlood))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnBloodRequest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbBloodRequest)
                            .addGap(357, 357, 357)
                            .addComponent(lbSeeAll))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbReport)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMenu)
                            .addComponent(lbNotification))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(banner)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDonate)
                                    .addComponent(lbOrderBlood))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFindDonor)
                                    .addComponent(lbHospital)))
                            .addComponent(lbDonateBlood))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBloodRequest)
                    .addComponent(lbSeeAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBloodRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbDonateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDonateMouseClicked
        // TODO add your handling code here:
      DonateOrderInbox inbox;
        try {
            inbox = new DonateOrderInbox(usr);
            inbox.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
dispose();
    }//GEN-LAST:event_lbDonateMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, URISyntaxException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomePage().setVisible(true);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbBloodRequest;
    private javax.swing.JLabel lbBloodType;
    private javax.swing.JLabel lbBtnDonate;
    private javax.swing.JLabel lbDonate;
    private javax.swing.JLabel lbDonateBlood;
    private javax.swing.JLabel lbFindDonor;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbHospital;
    private javax.swing.JLabel lbLocation;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNotification;
    private javax.swing.JLabel lbOrderBlood;
    private javax.swing.JLabel lbReport;
    private javax.swing.JLabel lbSeeAll;
    private javax.swing.JLabel lbTime;
    private javax.swing.JPanel pnBloodRequest;
    // End of variables declaration//GEN-END:variables
}
