/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rofat.blooddonation;

import com.rofat.blooddonation.Class.Api;
import dto.User;

import java.io.IOException;
import java.util.List;

/**
 * @author rofat
 */
public class Hospitals extends javax.swing.JFrame {

    /**
     * Creates new form BloodRequest
     */
    Api api = new Api();
    User usr = new User();
    List<User> hospital = api.getAllHospital();

    public Hospitals() throws IOException {
        initComponents();
        usr = api.getUser("rofat@gmail.com");
        loadData();
    }

    public Hospitals(User user) throws IOException {
        initComponents();
        usr = user;
        loadData();
    }

    private void loadData() throws IOException {

        for (int i = 0; i < hospital.size(); i++) {
            switch (i) {
                case 0:
                    txtHospitalName1.setText(hospital.get(i).getName());
                    txtContact1.setText(hospital.get(i).getContact().getPhoneNumber());
                    txtEmail1.setText(hospital.get(i).getEmail());
                    txtAddress1.setText(hospital.get(i).getAddress().toString());
                    pn2.setVisible(false);
                    pn3.setVisible(false);
                    pn4.setVisible(false);
                    break;
                case 1:
                    txtHospitalName2.setText(hospital.get(i).getName());
                    txtContact2.setText(hospital.get(i).getContact().getPhoneNumber());
                    txtEmail2.setText(hospital.get(i).getEmail());
                    txtAddress2.setText(hospital.get(i).getAddress().toString());
                    pn2.setVisible(true);
                    pn3.setVisible(false);
                    pn4.setVisible(false);

                    break;
                case 2:
                    txtHospitalName3.setText(hospital.get(i).getName());
                    txtContact3.setText(hospital.get(i).getContact().getPhoneNumber());
                    txtEmail3.setText(hospital.get(i).getEmail());
                    txtAddress3.setText(hospital.get(i).getAddress().toString());
                    pn3.setVisible(true);
                    pn4.setVisible(false);
                    break;
                case 3:
                    txtHospitalName4.setText(hospital.get(i).getName());
                    txtContact4.setText(hospital.get(i).getContact().getPhoneNumber());
                    txtEmail4.setText(hospital.get(i).getEmail());
                    txtAddress4.setText(hospital.get(i).getAddress().toString());
                    pn4.setVisible(true);
                    break;

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        pn1 = new javax.swing.JPanel();
        txtHospitalName1 = new javax.swing.JLabel();
        txtContact1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JLabel();
        pn2 = new javax.swing.JPanel();
        txtHospitalName2 = new javax.swing.JLabel();
        txtContact2 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JLabel();
        pn3 = new javax.swing.JPanel();
        txtHospitalName3 = new javax.swing.JLabel();
        txtContact3 = new javax.swing.JLabel();
        txtEmail3 = new javax.swing.JLabel();
        txtAddress3 = new javax.swing.JLabel();
        pn4 = new javax.swing.JPanel();
        txtHospitalName4 = new javax.swing.JLabel();
        txtContact4 = new javax.swing.JLabel();
        txtEmail4 = new javax.swing.JLabel();
        txtAddress4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(545, 700));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("HOSPITAL");

        btnSearch.setBackground(new java.awt.Color(255, 0, 0));
        btnSearch.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");

        txtSearch.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(204, 204, 204));
        txtSearch.setText("Hospital Name");

        pn1.setBackground(new java.awt.Color(255, 255, 255));

        txtHospitalName1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtHospitalName1.setText("Hospital's Name");

        txtContact1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtContact1.setText("Contact");

        txtEmail1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtEmail1.setText("Email");

        txtAddress1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtAddress1.setText("Address");

        javax.swing.GroupLayout pn1Layout = new javax.swing.GroupLayout(pn1);
        pn1.setLayout(pn1Layout);
        pn1Layout.setHorizontalGroup(
                pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pn1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHospitalName1)
                                        .addComponent(txtContact1)
                                        .addComponent(txtEmail1)
                                        .addComponent(txtAddress1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn1Layout.setVerticalGroup(
                pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pn1Layout.createSequentialGroup()
                                .addComponent(txtHospitalName1)
                                .addGap(2, 2, 2)
                                .addComponent(txtContact1)
                                .addGap(2, 2, 2)
                                .addComponent(txtEmail1)
                                .addGap(2, 2, 2)
                                .addComponent(txtAddress1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn2.setBackground(new java.awt.Color(255, 255, 255));

        txtHospitalName2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtHospitalName2.setText("Hospital's Name");

        txtContact2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtContact2.setText("Contact");

        txtEmail2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtEmail2.setText("Email");

        txtAddress2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtAddress2.setText("Address");

        javax.swing.GroupLayout pn2Layout = new javax.swing.GroupLayout(pn2);
        pn2.setLayout(pn2Layout);
        pn2Layout.setHorizontalGroup(
                pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pn2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHospitalName2)
                                        .addComponent(txtContact2)
                                        .addComponent(txtEmail2)
                                        .addComponent(txtAddress2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn2Layout.setVerticalGroup(
                pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pn2Layout.createSequentialGroup()
                                .addComponent(txtHospitalName2)
                                .addGap(2, 2, 2)
                                .addComponent(txtContact2)
                                .addGap(2, 2, 2)
                                .addComponent(txtEmail2)
                                .addGap(2, 2, 2)
                                .addComponent(txtAddress2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn3.setBackground(new java.awt.Color(255, 255, 255));

        txtHospitalName3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtHospitalName3.setText("Hospital's Name");

        txtContact3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtContact3.setText("Contact");

        txtEmail3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtEmail3.setText("Email");

        txtAddress3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtAddress3.setText("Address");

        javax.swing.GroupLayout pn3Layout = new javax.swing.GroupLayout(pn3);
        pn3.setLayout(pn3Layout);
        pn3Layout.setHorizontalGroup(
                pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pn3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHospitalName3)
                                        .addComponent(txtContact3)
                                        .addComponent(txtEmail3)
                                        .addComponent(txtAddress3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn3Layout.setVerticalGroup(
                pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pn3Layout.createSequentialGroup()
                                .addComponent(txtHospitalName3)
                                .addGap(2, 2, 2)
                                .addComponent(txtContact3)
                                .addGap(2, 2, 2)
                                .addComponent(txtEmail3)
                                .addGap(2, 2, 2)
                                .addComponent(txtAddress3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn4.setBackground(new java.awt.Color(255, 255, 255));

        txtHospitalName4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtHospitalName4.setText("Hospital's Name");

        txtContact4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtContact4.setText("Contact");

        txtEmail4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtEmail4.setText("Email");

        txtAddress4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtAddress4.setText("Address");

        javax.swing.GroupLayout pn4Layout = new javax.swing.GroupLayout(pn4);
        pn4.setLayout(pn4Layout);
        pn4Layout.setHorizontalGroup(
                pn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pn4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHospitalName4)
                                        .addComponent(txtContact4)
                                        .addComponent(txtEmail4)
                                        .addComponent(txtAddress4))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn4Layout.setVerticalGroup(
                pn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pn4Layout.createSequentialGroup()
                                .addComponent(txtHospitalName4)
                                .addGap(2, 2, 2)
                                .addComponent(txtContact4)
                                .addGap(2, 2, 2)
                                .addComponent(txtEmail4)
                                .addGap(2, 2, 2)
                                .addComponent(txtAddress4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\BloodDonation\\image\\hospital-banner.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(pn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(206, 206, 206)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSearch)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospitals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Hospitals().setVisible(true);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pn2;
    private javax.swing.JPanel pn3;
    private javax.swing.JPanel pn4;
    private javax.swing.JLabel txtAddress1;
    private javax.swing.JLabel txtAddress2;
    private javax.swing.JLabel txtAddress3;
    private javax.swing.JLabel txtAddress4;
    private javax.swing.JLabel txtContact1;
    private javax.swing.JLabel txtContact2;
    private javax.swing.JLabel txtContact3;
    private javax.swing.JLabel txtContact4;
    private javax.swing.JLabel txtEmail1;
    private javax.swing.JLabel txtEmail2;
    private javax.swing.JLabel txtEmail3;
    private javax.swing.JLabel txtEmail4;
    private javax.swing.JLabel txtHospitalName1;
    private javax.swing.JLabel txtHospitalName2;
    private javax.swing.JLabel txtHospitalName3;
    private javax.swing.JLabel txtHospitalName4;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
