/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rofat.blooddonation;

import com.rofat.blooddonation.Class.GlobalFuntions;

import java.util.HashMap;
import java.util.Map;

/**
 * @author rofat
 */
public class RegisterContact extends javax.swing.JFrame {

    /**
     * Creates new form testJframe
     */
    Map<String, Object> oldData = new HashMap<>();
    String[] fields = {"Email Address", "Facebook (Optional)", "Telegram (Optional)", "Phone Number 1", "Phone Number 2"};
    GlobalFuntions f = new GlobalFuntions(fields);

    public RegisterContact() {
        initComponents();
    }

    public RegisterContact(Map<String, Object> obj) {
        initComponents();
        oldData = obj;

        f.setObject(oldData);
        setFields();
        f.setForeColor(txtEmail);
        f.setForeColor(txtFacebook);
        f.setForeColor(txtTelegram);
        f.setForeColor(txtPhone1);
        f.setForeColor(txtPhone2);
    }

    private Map<String, Object> setObject() {
        Map<String, Object> obj = new HashMap<>();
        obj.put("Email Address", txtEmail.getText());
        obj.put("Facebook (Optional)", txtFacebook.getText());
        obj.put("Telegram (Optional)", txtTelegram.getText());
        obj.put("Phone Number 1", txtPhone1.getText());
        obj.put("Phone Number 2", txtPhone2.getText());
        return obj;
    }

    private void setFields() {
        f.checkAndAssignValueToTF(txtEmail, "Email Address");
        f.checkAndAssignValueToTF(txtFacebook, "Facebook (Optional)");
        f.checkAndAssignValueToTF(txtTelegram, "Telegram (Optional)");
        f.checkAndAssignValueToTF(txtPhone1, "Phone Number 1");
        f.checkAndAssignValueToTF(txtPhone2, "Phone Number 2");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        banner = new javax.swing.JLabel();
        lbContact = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        basicInfoPnl = new javax.swing.JPanel();
        txtPhone1 = new javax.swing.JTextField();
        txtPhone2 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelegram = new javax.swing.JTextField();
        txtFacebook = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 700));

        banner.setBackground(new java.awt.Color(153, 0, 102));
        banner.setForeground(new java.awt.Color(153, 0, 153));
        banner.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        banner.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\testing\\image\\Register-banner.png")); // NOI18N
        banner.setToolTipText("");
        banner.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbContact.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lbContact.setForeground(new java.awt.Color(204, 0, 0));
        lbContact.setText("CONTACT");
        lbContact.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }

            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbContactAncestorAdded(evt);
            }

            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnPrevious.setBackground(java.awt.Color.red);
        btnPrevious.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setBackground(java.awt.Color.red);
        btnNext.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        basicInfoPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPhone1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtPhone1.setForeground(new java.awt.Color(204, 204, 204));
        txtPhone1.setText("Phone Number 1");
        txtPhone1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhone1MouseClicked(evt);
            }
        });

        txtPhone2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtPhone2.setForeground(new java.awt.Color(204, 204, 204));
        txtPhone2.setText("Phone Number 2");
        txtPhone2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhone2MouseClicked(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setText("Email Address");
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });

        txtTelegram.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTelegram.setForeground(new java.awt.Color(204, 204, 204));
        txtTelegram.setText("Telegram (Optional)");
        txtTelegram.setToolTipText("");
        txtTelegram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelegramMouseClicked(evt);
            }
        });

        txtFacebook.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtFacebook.setForeground(new java.awt.Color(204, 204, 204));
        txtFacebook.setText("Facebook (Optional)");
        txtFacebook.setToolTipText("");
        txtFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFacebookMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout basicInfoPnlLayout = new javax.swing.GroupLayout(basicInfoPnl);
        basicInfoPnl.setLayout(basicInfoPnlLayout);
        basicInfoPnlLayout.setHorizontalGroup(
                basicInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(basicInfoPnlLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(basicInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelegram, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(27, Short.MAX_VALUE))
        );
        basicInfoPnlLayout.setVerticalGroup(
                basicInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(basicInfoPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelegram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(banner)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(basicInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(lbContact))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(130, 130, 130)
                                                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(banner)
                                .addGap(7, 7, 7)
                                .addComponent(lbContact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(basicInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnPrevious)
                                        .addComponent(btnNext))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFacebookMouseClicked
        // TODO add your handling code here:
        f.clearTextBox(txtFacebook);
    }//GEN-LAST:event_txtFacebookMouseClicked

    private void txtTelegramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelegramMouseClicked
        // TODO add your handling code here:
        f.clearTextBox(txtTelegram);
    }//GEN-LAST:event_txtTelegramMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
        f.clearTextBox(txtEmail);
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtPhone2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhone2MouseClicked
        // TODO add your handling code here:
        f.clearTextBox(txtPhone2);
    }//GEN-LAST:event_txtPhone2MouseClicked

    private void txtPhone1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhone1MouseClicked
        // TODO add your handling code here:
        f.clearTextBox(txtPhone1);
    }//GEN-LAST:event_txtPhone1MouseClicked

    private void lbContactAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbContactAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbContactAncestorAdded

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        oldData.putAll(setObject());
        RegisterLoginInfo jframe = new RegisterLoginInfo(oldData);
        jframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        oldData.putAll(setObject());
        RegisterAddress jframe = new RegisterAddress(oldData);
        jframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JPanel basicInfoPnl;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel lbContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFacebook;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtPhone2;
    private javax.swing.JTextField txtTelegram;
    // End of variables declaration//GEN-END:variables
}
